### ISSUE TITLE
Error in onSignal

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#41]
when doing 
```js
computer.onSignal('', function () {
    computer.error('Hello from onsignal-nothing');
});
```
it crashes (ingame pc) with (log)
```
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: javax.script.ScriptException: TypeError: computer.next is not a function in <eval> at line number 68
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at javax.script.AbstractScriptEngine.eval(Unknown Source)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:54)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.lang.Thread.run(Unknown Source)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: <eval>:68 TypeError: computer.next is not a function
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.scripts.Script$2029$\^eval\_.:program(<eval>:68)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
[19:58:16] [OpenComputers-Computer-3/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 9 more
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.runtime.ScriptFunction to [Ljava.lang.Object;
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.lang.invoke.MethodHandleImpl.newClassCastException(Unknown Source)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.lang.invoke.MethodHandleImpl.castReference(Unknown Source)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.internal.scripts.Script$2108$\^eval\_.:program(<eval>:68)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at javax.script.AbstractScriptEngine.eval(Unknown Source)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:54)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:00:29] [OpenComputers-Computer-2/INFO] [STDERR]: [me.mrmakeit.ocjs.NashornAPI:runThreaded:89]: 	at java.lang.Thread.run(Unknown Source)
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶLast errorȦ: Cannot cast jdk.nashorn.internal.runtime.ScriptFunction to [Ljava.lang.Object;
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶNumber of connected componentsȦ: 5/16
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶStored energyȦ: 446.94/500.00
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶTotal stored energyȦ: 946.94/1000.00
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶComponent nameȦ: computer
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] ǶAddressȦ: 54caa649-f011-481a-aaf7-c62a512ff20d
[20:00:36] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Address copied to clipboard.
```

**Comment by mrmakeit** [comment]
I had hoped that having onSignal as a separate header would make it clear that it is a global value.  I'll add an example to the wiki, but in the mean time: 
```
onSignal = function(name,args...){
  computer.print("Got signal "+name);
}
```

The signals are from OpenComputers, see https://ocdoc.cil.li/component:signals

**Comment by hasezoey** [comment]
i have yet
```js
onSignal('key_down', function (addr, char, code, pn) {
    write('KEYDOWN');
});
```
but when i do something, there always comes the error "No Event Loop"

**Comment by hasezoey** [comment]
i have yet
(write is my functions that prints to screen)
```js
function onSignal(name, args) {
    write('GOT SIGNAL '+name);
}
onSignal('key_down', function (addr, char, code, pn) {
    write('KEYDOWN');
});
```
and only "KEYDOWN" is coming (without pushing something
and when pushing something "No event loop"

**Comment by mrmakeit** [comment]
you have to use the assignment format `onSignal = function()` as the other overloads the value in scope, and for onSignal to be called correctly, you have to replace the global format.

**Comment by hasezoey** [comment]
ok, yet it is working ... could it be added outside of the eeprom (before the eeprom is loaded? this would make more sense)

**Comment by hasezoey** [comment]
found critical error when doing:
```js
onSignal = function (args) {
    write('GOT SIGNAL ' + name + " " + JSON.stringify(args));
}
```
it throws
```
[10:43:37] [OpenComputers-Computer-4/WARN] [opencomputers]: Architecture's runThreaded threw an error. This should never happen!
jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "name" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[ECMAErrors.class:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319) ~[ECMAErrors.class:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291) ~[ECMAErrors.class:?]
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1428) ~[Global.class:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$2669$2259AA$\^eval\_#93\!9\^eval\_.onSignal(<eval>#93:9<eval>:68) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:625) ~[ScriptFunctionData.class:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[ScriptFunction.class:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[ScriptRuntime.class:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[ScriptObjectMirror.class:?]
	at me.mrmakeit.ocjs.NashornAPI.runThreaded(NashornAPI.java:111) ~[NashornAPI.class:?]
	at me.mrmakeit.ocjs.NashornArch.runThreaded(NashornArch.java:44) ~[NashornArch.class:?]
	at li.cil.oc.server.machine.Machine.run(Machine.scala:967) [Machine.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

```

**Comment by mrmakeit** [comment]
First value passed to the function is the signal name, and all arguments passed after that are from the signal itself.  The easiest format i have found is:
```
onSignal = function(){
  var name = arguments.shift();
  var args = arguments;
}
```
also, you didn't define name in the function parameters;

**Comment by hasezoey** [comment]
when doing this
```js
onSignal = function () {
    write('GOT SIGNAL ' + JSON.stringify(arguments));
}
```
it works fine, should this be added before the eeprom loads?

**Comment by mrmakeit** [comment]
no, as the function is for adding signal based event loops.  If no function is set on first boot, the computer should automatically shutdown.

**Comment by hasezoey** [comment]
also when i dont add "onSignal" until i push something (like a key or so) it dont throws an error ("No event loop")

**Comment by mrmakeit** [comment]
Yep.  the onSignal is the event loop.  no value means no event loop.

**Comment by hasezoey** [comment]
i mean when i dont define / call onSignal it dont shutdown

**Comment by mrmakeit** [comment]
Oh, misread your comment.  Since the arch goes into deep sleep by default, it cant check for onSignal till.an event triggers it.  I'll likely change from deep sleep to 0 tick sleep to alleviate this, as the user can change it back anytime.
