### ISSUE TITLE
No Event Loop on startup and FileNotFound for /init.js

### ISSUE THREAD

**Issue by Clemens-E** [mrmakeit/OCJS#63]
Hi, I'm not sure if this project is even maintained at all, but my friends and me really hate lua so this is my only chance.
We set up a PC, added a CPU (with ES5) and a JS Bios, when starting the PC we get
"No Event Loop" and this error in the server console:
```
[pool-14-thread-1/INFO] [STDOUT]: [me.mrmakeit.ocjs.ComputerAPI:invoke:26]: Running open on 35c85b6e-4926-40ff-977d-1173a7b3002f
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]: java.io.FileNotFoundException: /init.js
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.fs.InputStreamFileSystem$class.open(InputStreamFileSystem.scala:43)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.fs.FileSystem$BufferedFileSystem.li$cil$oc$server$fs$OutputStreamFileSystem$$super$open(FileSystem.scala:191)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.fs.OutputStreamFileSystem$class.open(OutputStreamFileSystem.scala:24)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.fs.FileSystem$BufferedFileSystem.open(FileSystem.scala:191)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.component.FileSystem.open(FileSystem.scala:165)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at generated.li.cil.oc.CallWrapper_li_cil_oc_server_component_FileSystem_open.call(Unknown Source)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.network.Component$class.invoke(Component.scala:112)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.network.Network$ComponentConnectorBuilder$$anon$1.invoke(Network.scala:636)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at li.cil.oc.server.machine.Machine.invoke(Machine.scala:380)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at me.mrmakeit.ocjs.ComputerAPI.invoke(ComputerAPI.java:28)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.scripts.Script$Recompilation$1358$573AA$\^eval\_.loadFrom(<eval>:23)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.scripts.Script$Recompilation$1353$1501$\^eval\_.init(<eval>:64)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.scripts.Script$1352$\^eval\_.:program(<eval>:70)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:54)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[pool-14-thread-1/INFO] [STDERR]: [me.mrmakeit.ocjs.ComputerAPI:invoke:36]:  at java.lang.Thread.run(Thread.java:748)
```
The last call that is made by OCJS happens in [this line](https://github.com/mrmakeit/OCJS/blob/master-1.10.2/src/main/java/me/mrmakeit/ocjs/ComputerAPI.java#L28,) and then OC tries to read /init.js as it seems?

I was not able to find any Issue in here that had the same Problem.
We tried every OC version ranging from
1.7.2.67 to 1.7.5.192

**Comment by hasezoey** [comment]
i dont think this project is maintained any longer (and from what i know, opencomputers didnt update as well to ~1.14)

there are many problems with the current state of this project, main one being that es6 is not working *at all*, and that there isnt much documentation or errors with description

but if you want to look into how you can get it at least a bit working, i [made an OS with this](https://github.com/hasezoey/OCJS_OS), or at least tried, because i didnt have the knowhow yet on how to make something with opencomputers, and this project didnt really provide an api that was useable in an good way - and on top of all of that, the limits set from opencomputers often hit (like not enough ram / cpu, even thought i was using the highest items available)

oh and, if you somehow should do an mistake and forget an quirk and ran the scripts, it could very well be that the whole world / server locked up until manually killed and restarted

**Comment by Clemens-E** [comment]
Sad, I really wouldn't like to learn lua just for some Minecraft mods.
We ran this in Minecraft 1.12.2 btw, so I thought it would work, but doesn't seem like it.

**Comment by mrmakeit** [comment]
hey, sorry for the absense.  Unfortunently, yes this project is no longer maintained.  I can however, offer some insight into the issue.  This particular error seems to indicate that yoi simply dont have a /init.js file in amy filesystem attached to the computer.  OCJS never got to a point of having clear messages, so often looking at the console is a better way to understand what is going wrong.
